### ISSUE TITLE
Define Controls for Selecting Modes

### ISSUE THREAD

**Issue by emilylhsieh** [emilylhsieh/FTC-Team-25#2]
- Servo
- Drive Motors
- Independent Motors
- Servo with Drive Motors
- Servo with Independent Motors

The purpose of this task is to define which tasks will be performed with the modes above.

**Comment by Ashdalisay** [comment]
- Drive Mode uses 4 motors and joysticks X and Y to drive the motors in tank drive mode
- Independent motor mode 
  - use colored buttons for toggling motor selection 
    - no push not driving motor 
    - one push clockwise 
    - two push counter clockwise 
    - third push not driving motor
  - use right trigger to drive the motor 
- Servo Mode 
  - multiple servos
  - D pad button selects Servo to drive
  - pressing D pad button toggles the direction (stop, clockwise, counter clockwise)
- Drive Mode with multiple servos
- Independent motor mode
  -

**Comment by h0llycarter** [comment]
controls documented [here](https://docs.google.com/presentation/d/1XQdS9bsbJl9jDMp0p6gLKDiS0oPpkCvcxPJz67N7tEA/edit?usp=sharing)
